### ISSUE TITLE
No match for `darkroom-mode`

### ISSUE THREAD

**Issue by IbrahimFadel** [capitaomorte/darkroom#14]
Hi there,

I recently started learning how to use emacs. I've installed darkroom, but unfortunately i'm unable to enter `darkroom-mode`

I installed like this:

```M-x package-install darkroom```

When i list my installed packages, it shows up, and I can find `darkroom.el`. However, when i try to enter darkroom mode:

```M-x darkroom-mode```

It doesn't work. It says: ```match-required```
As in, the mode doesn't exist.
Is there any reason for this?

Here is my init.el:

```
(setq gc-cons-threshold most-positive-fixnum)

;; In noninteractive sessions, prioritize non-byte-compiled source files to
;; prevent the use of stale byte-code. Otherwise, it saves us a little IO time
;; to skip the mtime checks on every *.elc file.
(setq load-prefer-newer noninteractive)

(let (file-name-handler-alist)
  ;; Ensure Doom is running out of this file's directory
  (setq user-emacs-directory (file-name-directory load-file-name)))

;; Load the heart of Doom Emacs
(load (concat user-emacs-directory "core/core")
      nil 'nomessage)

(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)

(add-to-list 'load-path "~/.emacs.d/emacs-neotree")
(require 'neotree)
(global-set-key [f8] 'neotree-toggle)

(add-to-list 'load-path "~/.emacs.d/dired+.el")
;(require 'dired+)

(global-set-key (kbd "S-<f1>")
  (lambda ()
    (interactive)
    (dired "~/")))

(setq doom-font (font-spec :family "JetBrains Mono" :size 12))

(add-hook 'c++-mode-hook 'irony-mode)
(add-hook 'c-mode-hook 'irony-mode)
(add-hook 'objc-mode-hook 'irony-mode)

(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)

(eval-after-load 'company
  '(add-to-list 'company-backends 'company-irony))

;; And let 'er rip!
(doom-initialize)
```

**Comment by IbrahimFadel** [comment]
Nevermind I figured it out,

For anyone wondering, i added the following to my ```init.el```

```
(add-to-list 'load-path "~/.emacs.d/.local/elpa/darkroom-0.3")
(require 'darkroom)                                                                                                                                
(add-hook 'prog-mode 'darkroom-tentative-mode)  
```

I'm not sure if this is the proper way to do this, but it works for me now

**Comment by c256** [comment]
FWIW, this setting:

On Tue, May 26, 2020 at 7:41 AM Ibrahim Fadel <notifications@github.com>
wrote:

> Here is my init.el:
>
> (setq gc-cons-threshold most-positive-fixnum)
>
> Absolutely *will* result in worse performance over time. The effect this
has is to tell emacs "Don't perform garbage collection until things are so
bad that it will freeze emacs for a significant amount of real-world time."

For people who use lots of packages, or otherwise have very large setups,
it's entirely possible to improve real performance by turning the threshold
off *during setup*, and then turning it back down to something reasonable
after setup (i.e. when you want to actually interact with emacs). It's also
possible to improve real-world performance by raising the number above
emacs' (very conservative) default value. For my own setup, I do a couple
things to speed up startup, and to set a larger interactive use value:

;; Avoid excessive GC's during init
> (setq gc-cons-threshold (* 256 1024 1024))
> (setq gc-cons-percentage 0.6)
>


;; Set up a hook to restore interactive-use settings
> (add-hook 'after-init-hook
>  `(lambda ()
>     (setq gc-cons-threshold (* 64 1024 1024))
>     (setq gc-cons-percentage 0.1)
>     (garbage-collect)) t)


I hope that helps!
~Chad

**Comment by IbrahimFadel** [comment]
Thank you, I didn't know that
